<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE LabyrinthLevel [
    <!ELEMENT LabyrinthLevel (Name, InstructionFile?, Dimension, Labyrinth?, Create?, Style?)>
    <!ELEMENT Name (#PCDATA)>
    <!ELEMENT InstructionFile (#PCDATA)>
    <!ELEMENT Dimension (width, height)>
    <!ELEMENT width (#PCDATA)>
    <!ELEMENT height (#PCDATA)>
    <!ELEMENT Labyrinth (StartSymbol, WallSymbol, DiamondSymbol, WaySymbol, ZeroSymbol, OneSymbol, TwoSymbol, ThreeSymbol, SymbolList?, StartingDirection, LabyrinthField)>
    <!ELEMENT StartSymbol (#PCDATA)>
    <!ELEMENT WallSymbol (#PCDATA)>
    <!ELEMENT DiamondSymbol (#PCDATA)>
    <!ELEMENT WaySymbol (#PCDATA)>
    <!ELEMENT ZeroSymbol (#PCDATA)>
    <!ELEMENT OneSymbol (#PCDATA)>
    <!ELEMENT TwoSymbol (#PCDATA)>
    <!ELEMENT ThreeSymbol (#PCDATA)>
    <!ELEMENT SymbolList (Symbol*)>
    <!ELEMENT Symbol (CharSymbol, StringSymbol)>
    <!ELEMENT CharSymbol (#PCDATA)>
    <!ELEMENT StringSymbol (#PCDATA)>
    <!ELEMENT StartingDirection (#PCDATA)>
    <!ELEMENT LabyrinthField (#PCDATA)>
    <!ELEMENT Create (Diamonds, WayCells, MinWayLenght, MaxWayLenght, BuildAngles, BuildTrees, BuildLoops, BuildPlaces)>
    <!ELEMENT Diamonds (#PCDATA)>
    <!ELEMENT WayCells (#PCDATA)>
    <!ELEMENT MinWayLenght (#PCDATA)>
    <!ELEMENT MaxWayLenght (#PCDATA)>
    <!ELEMENT BuildAngles (#PCDATA)>
    <!ELEMENT BuildTrees (#PCDATA)>
    <!ELEMENT BuildLoops (#PCDATA)>
    <!ELEMENT BuildPlaces (#PCDATA)>
    <!ELEMENT Style (WallPicture, WayPicture, RobotPicture, DiamondPicture, StartPicture)>
    <!ELEMENT WallPicture (#PCDATA)>
    <!ELEMENT WayPicture (#PCDATA)>
    <!ELEMENT RobotPicture (#PCDATA)>
    <!ELEMENT DiamondPicture (#PCDATA)>
    <!ELEMENT StartPicture (#PCDATA)>
]>
<LabyrinthLevel>
  <Name> Labyrinth 8 </Name>
  <Dimension>
    <width> 20 </width>
    <height> 20 </height>
  </Dimension>
  <Labyrinth>
    <StartSymbol> S </StartSymbol>
    <WallSymbol> W </WallSymbol>
    <DiamondSymbol> D </DiamondSymbol>
    <WaySymbol> . </WaySymbol>
    <ZeroSymbol> 0 </ZeroSymbol>
    <OneSymbol> 1 </OneSymbol>
    <TwoSymbol> 2 </TwoSymbol>
    <ThreeSymbol> 3 </ThreeSymbol>
    <StartingDirection> UP </StartingDirection>
    <LabyrinthField>
      WWWWWWWWWWWWWWWWWWWW
      W............D..D.WW
      W.WWWWWWWWWWWWWWWDWW
      W.WWWWWWWWWWWWWWWDWW
      W.WWWWWWWWW..D..W.WW
      W...WWWWWWW.W.WW..WW
      W.W.WWWWWWW.WWW.W.WW
      W........D........WW
      WWW.WDWWWWWWWWWWW.WW
      W...WDD...D...WWW..W
      W.W.W.WWWW.WWWWWWDWW
      W.W.W.W....WWWWWW.WW
      WWW.WWWWWWWWWWWWW.WW
      WDD.........D..D..WW
      W.WWWWWW.WWWDWWWWW.W
      WD....WW.WWW.WDD..DW
      W.W.W....WWW.WWWWW.W
      W.W.W.WW.W.........W
      W.W.W....WWWWWWWWWWW
      WSWWWWWWWWWWWWWWWWWW
    </LabyrinthField>
  </Labyrinth>
</LabyrinthLevel>