<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE LabyrinthLevel [
    <!ELEMENT LabyrinthLevel (Name, InstructionFile?, Dimension, Labyrinth?, Create?, Style?)>
    <!ELEMENT Name (#PCDATA)>
    <!ELEMENT InstructionFile (#PCDATA)>
    <!ELEMENT Dimension (width, height)>
    <!ELEMENT width (#PCDATA)>
    <!ELEMENT height (#PCDATA)>
    <!ELEMENT Labyrinth (StartSymbol, WallSymbol, DiamondSymbol, WaySymbol, ZeroSymbol, OneSymbol, TwoSymbol, ThreeSymbol, SymbolList?, StartingDirection, LabyrinthField)>
    <!ELEMENT StartSymbol (#PCDATA)>
    <!ELEMENT WallSymbol (#PCDATA)>
    <!ELEMENT DiamondSymbol (#PCDATA)>
    <!ELEMENT WaySymbol (#PCDATA)>
    <!ELEMENT ZeroSymbol (#PCDATA)>
    <!ELEMENT OneSymbol (#PCDATA)>
    <!ELEMENT TwoSymbol (#PCDATA)>
    <!ELEMENT ThreeSymbol (#PCDATA)>
    <!ELEMENT SymbolList (Symbol*)>
    <!ELEMENT Symbol (CharSymbol, StringSymbol)>
    <!ELEMENT CharSymbol (#PCDATA)>
    <!ELEMENT StringSymbol (#PCDATA)>
    <!ELEMENT StartingDirection (#PCDATA)>
    <!ELEMENT LabyrinthField (#PCDATA)>
    <!ELEMENT Create (Diamonds, WayCells, MinWayLenght, MaxWayLenght, BuildAngles, BuildTrees, BuildLoops, BuildPlaces)>
    <!ELEMENT Diamonds (#PCDATA)>
    <!ELEMENT WayCells (#PCDATA)>
    <!ELEMENT MinWayLenght (#PCDATA)>
    <!ELEMENT MaxWayLenght (#PCDATA)>
    <!ELEMENT BuildAngles (#PCDATA)>
    <!ELEMENT BuildTrees (#PCDATA)>
    <!ELEMENT BuildLoops (#PCDATA)>
    <!ELEMENT BuildPlaces (#PCDATA)>
    <!ELEMENT Style (WallPicture, WayPicture, RobotPicture, DiamondPicture, StartPicture)>
    <!ELEMENT WallPicture (#PCDATA)>
    <!ELEMENT WayPicture (#PCDATA)>
    <!ELEMENT RobotPicture (#PCDATA)>
    <!ELEMENT DiamondPicture (#PCDATA)>
    <!ELEMENT StartPicture (#PCDATA)>
]>
<LabyrinthLevel>
  <Name> Labyrinth 10 </Name>
  <Dimension>
    <width> 20 </width>
    <height> 20 </height>
  </Dimension>
  <Labyrinth>
    <StartSymbol> S </StartSymbol>
    <WallSymbol> W </WallSymbol>
    <DiamondSymbol> D </DiamondSymbol>
    <WaySymbol> . </WaySymbol>
    <ZeroSymbol> 0 </ZeroSymbol>
    <OneSymbol> 1 </OneSymbol>
    <TwoSymbol> 2 </TwoSymbol>
    <ThreeSymbol> 3 </ThreeSymbol>
    <StartingDirection> UP </StartingDirection>
    <LabyrinthField>
WWWWWWWWWWWWWWWWWWWW
W..................W
W..WWWWDWW.WWW.....W
W..W..W.WW.W.WWWWW.W
W..W.WW.WW.W.WWWWW.W
W..W.WW.WW.W.WWWWW.W
W..WD...WW..D.WD...W
W.WWWWWWWWWWWWW...WW
W.WWWWWWWWWWWWW.WW.W
W.WWWWWWWWWWWWW.D..W
W...W..D......D.WWWW
W.WWW.W.WWWW......WW
W...W.W.WW.W..WWW.WW
W.WWW.W.WW.W...DW.WW
WD.WW.WWWW.WWWWWW.WW
W..WWD............WW
W..WWWWWW.WWWWWWWWWW
W..WWWWWW.WWWWWWWWWW
W.......W.WWWWWWWWWW
WWWWWWWWWSWWWWWWWWWW
    </LabyrinthField>
  </Labyrinth>
</LabyrinthLevel>