<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE LabyrinthInstructionTXT [
    <!ELEMENT LabyrinthInstructionTXT (ConditionStartString, ConditionEndString, ActionStartString, ActionEndString, ConditionActionSeparatorString, SeparatorString, CommentOutLineString, CommentOutStartString, CommentOutEndString, DeactivateInstructionString, WallString, WayString, DirectionLeftString, DirectionAheadString, DirectionRightString, DirectionBackString)>
    <!ELEMENT ConditionStartString (#PCDATA)>
    <!ELEMENT ConditionEndString (#PCDATA)>
    <!ELEMENT ActionStartString (#PCDATA)>
    <!ELEMENT ActionEndString (#PCDATA)>
    <!ELEMENT ConditionActionSeparatorString (#PCDATA)>
    <!ELEMENT SeparatorString (#PCDATA)>
    <!ELEMENT CommentOutLineString (#PCDATA)>
    <!ELEMENT CommentOutStartString (#PCDATA)>
    <!ELEMENT CommentOutEndString (#PCDATA)>
    <!ELEMENT DeactivateInstructionString (#PCDATA)>
    <!ELEMENT WallString (#PCDATA)>
    <!ELEMENT WayString (#PCDATA)>
    <!ELEMENT DirectionLeftString (#PCDATA)>
    <!ELEMENT DirectionAheadString (#PCDATA)>
    <!ELEMENT DirectionRightString (#PCDATA)>
    <!ELEMENT DirectionBackString (#PCDATA)>
]>
<LabyrinthInstructionTXT>
  <ConditionStartString> ( </ConditionStartString>
  <ConditionEndString> ) </ConditionEndString>
  <ActionStartString> ( </ActionStartString>
  <ActionEndString> ) </ActionEndString>
  <ConditionActionSeparatorString> -> </ConditionActionSeparatorString>
  <SeparatorString> , </SeparatorString>
  <CommentOutLineString> // </CommentOutLineString>
  <CommentOutStartString> /* </CommentOutStartString>
  <CommentOutEndString> */ </CommentOutEndString>
  <DeactivateInstructionString> # </DeactivateInstructionString>
  <WallString> f </WallString>
  <WayString> g </WayString>
  <DirectionLeftString> nach links </DirectionLeftString>
  <DirectionAheadString> nach vorn </DirectionAheadString>
  <DirectionRightString> nach rechts </DirectionRightString>
  <DirectionBackString> umdrehen </DirectionBackString>
</LabyrinthInstructionTXT>